version: "1"
rules:
  - base: main
    upstream: blender:main
    mergeMethod: merge
  - base: blender-v3.6-release
    upstream: blender:blender-v3.6-release
    mergeMethod: merge
  - base: blender-v3.3-release
    upstream: blender:blender-v3.3-release
    mergeMethod: merge
  - base: blender-v4.0-release
    upstream: blender-v4.0-release
    mergeMethod: merge
